---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: service
spec:
  ports:
    - name: http
      port: 9090
  selector:
    app: prometheus
    component: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
      component: service
  template:
    metadata:
      labels:
        app: prometheus
        component: service
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: kafka-client-msk-sasl-scram-serviceaccount
      containers:
        - image: ubuntu:21.10
          name: prometheus
          command: [ "/bin/sh" ]
          args: [ "-c", "tail -f /dev/null" ]
          ports:
            - containerPort: 9090
          imagePullPolicy: IfNotPresent
---